import random

CHARS = [chr(i) for i in range(ord('A'), ord('Z'))] + [chr(i) for i in range(ord('a'), ord('z'))]
NAMES = [
    "Adept",
    "Arbiter",
    "Archon",
    "Carrier",
    "Colossus",
    "Corsair",
    "Dark Archon",
    "Dark Templar",
    "Disruptor",
    "Dragoon",
    "High Templar",
    "Immortal",
    "Observer",
    "Oracle",
    "Phoenix",
    "Photon Cannon",
    "Probe",
    "Reaver",
    "Scout",
    "Shuttle",
    "Stalker",
    "Tempest",
    "Void Ray",
    "Warp Prism",
    "Zealot",
    "Battlecruiser",
    "Cyclone",
    "Dropship",
    "Firebat",
    "Ghost",
    "Goliath",
    "Hellion",
    "Hellbat",
    "Liberator",
    "Marauder",
    "Marine",
    "Medic",
    "Medivac",
    "Missile Turret",
    "Raven",
    "Reaper",
    "Science Vessel",
    "SCV",
    "Siege Tank",
    "Thor",
    "Valkyrie",
    "Viking",
    "Vulture",
    "Widow Mine",
    "Wraith",
    "Broodling",
    "Brood Lord",
    "Corruptor",
    "Defiler",
    "Devourer",
    "Drone",
    "Guardian",
    "Hydralisk",
    "Infested Terran",
    "Infestor",
    "Larva",
    "Lurker",
    "Mutalisk",
    "Overlord",
    "Overseer",
    "Queen",
    "Ravager",
    "Roach",
    "Scourge",
    "Spore Colony",
    "Sunken Colony",
    "Ultralisk",
    "Viper",
    "Zergling",
]

class TournamentIdGenerator:

    @staticmethod
    def next_id() -> str:
        return "".join(random.choice(CHARS) for _ in range(8))

    @staticmethod
    def next_name() -> str:
        return "The {} Cup".format(random.choice(NAMES))
